# This file is managed by 'repo_helper'. Don't edit it directly.
---

os: linux
language: python
dist: focal
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10-dev'

arch:
  - amd64
  - arm64
install:

  - pip install --upgrade pip
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox -vv
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi


jobs:
  allow_failures:
    - arch: arm64
    - python: ['3.10-dev']

  exclude:
    - python: '3.7'
      arch: arm64
    - python: '3.8'
      arch: arm64
    - python: '3.9'
      arch: arm64
    - python: '3.10-dev'
      arch: arm64

  include:
    - stage: test
      dist: bionic
      python: 3.8

    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/default_values
        provider: pypi
        username: "DomDF"
        password:
          secure: Q3JxpZNAtfAIhepsoypTFQxJTaAH1rh5SuOcWjat3BSn7Clzj8oKc+cigP5NOuY39NBRL4veDt3GfU2xg1/94hZKc42e6e5qEm6062g+WZWFdQjpCSZIjk/ZUOwhKwOV9tBysEw1MPNbsTi4GUD81dv4fDuOJsj29TeQzOwAahxzTMdJeqU1xnaZUC5ewGfjDzmjHD73Q1AFuVtvZV4OoVEMpAO3W2LcKMvoKUyzskG0IX+WkcB9nQMYotuxWrOQmum5DPw1P+j1RKJzWa6k+CNF+SXxiOueUwcZL6xWospGa4sPWC7LjSk8USGAyV/WHAirWCjY1CTAl2BLQuTxx3KLl7YKDMXwcMkG/K40kvn68gXCZbFxiBbXDJuFW+2j3IIWJ4g6sFv2n+L5KsT6YMwZAGNcA61ylKZ0MGX/P6jBKWCGvRrbhvEx1Oecr/3JNfejLglOPRPwuFpmkQ4xqEzhsQfaQ32Q624wvhoRKnAjPAeUGBI16/+d6vLhXngRXkLEjgJADRwDQ8t2Ed7XdlfMm+JhdV19P0lkXxsOxe9nmGYJSU5WD4Mb+IxQZUgXgzYk+kZaQHO+pmbKNXgO/qP61I0Zce90XEcIOJB1zGk9POE+/83AFbvSAzz6TrA4vRtfFpLcQbgjBTJhXRlEYgSdAqPERmNaoVMKUgre/1w=
        distributions: "sdist bdist_wheel"
        skip_existing: true
